### ISSUE TITLE
Possible colaboration

### ISSUE THREAD

**Issue by AlexS12** [AlexS12/FlightMechanics.jl#34]
Hi, @parthp08. Let's open an issue here and talk about possible collaboration in the implementation of a Julia Flight Mechanics package.

My name is Alex and I am from Spain. I am an aerospace engineer, currently working at Airbus. I have always been passionate about scientific programming specially in Python, although lately I have become very interested in Julia. I can also do some Fortran and Matalb. For me this project is just a nice way to continue learning both programming and Flight Mechanincs. Being able to program and reproduce many of the methods described in Stevens is for me a very rewarding way of learning, but I don't always have all the time I would like to do it. 

My main idea when I started this repo was to develop a flight simulator similar to what you already saw in PyFME (https://github.com/AeroPython/PyFME) while learning and practicing Julia. I performed a big sprint last Christmas (this is just a personal project for me) and implemented some of the basic reference frame conversions, the F16 Steven's model and the trimmer. I spent quite a big time on testing and I would say that's the most valuable part of the project until now. In fact, I checked that the error you found in PyFME is not present here :sweat_smile:

The next step I had in mind was the implementation of the propagation, so "the aircraft could start flying" finally!

As this was my first "big project" in Julia, I feel less proud of the code structure:
 - I don't really see now if the models (src/models) I created are useful, make sense and generalize
 - I don't really trust the modules structure I implemented at first
 - Some methods are not exported where they should be and maybe some includes don'r really make sense.
So I think there is still a lot of effort  on making out of this repo a nice and useful package.

I will take some time to explore https://github.com/parthp08/Aircraft-Control-and-Simulation but I have seen you have progressed much more than me in the integration and control subjects. Is that the part you are more interested in? I have always wanted a control loop in the simulators I have implemented, but I have always got lost in the previous details. 

I guess some collaboration would really lead to a more continuous, sustainable and promising development. :smiley:

Would you like to share some info about your background, objectives, roadmap for the project... or any other thing you consider important?

**Comment by parthp08** [comment]
hi, i am Parth and i'm from India. i have completed by bachelor degree in Aeronautical engg. and i will be going to Canada for masters. I started working on code for stevens book for learning and improving programming skills and also because of my interest in flight mechanics.  I also choose julia because i wanted to learn it and don't wont to do basic tutorials or that kind of stuff.
as for the future work for this repo i think adding autopilots and control system methods based on stevens book will be good and there is already good control system library in julia pkgs. and if you like to expand this repo in that direction right now i have some free time until i starts my masters, so i will be able to do some work.

**Comment by parthp08** [comment]
and as for my repo with 3DoF, that is just basic stuff that was in the book, i am currently working on https://github.com/stanleybak/AeroBenchVVPython.git . check it out it is good but has a some errors in calculation and its in python 2. so currently removing bugs and converting it to python 3.

**Comment by AlexS12** [comment]
Great! Nice to meet you! 

Do you think we could try to integrate some of the work you did here? I would say RK and linearization would really fit so that we could afterwards implement the simulation loop and leave a gap for the controller such as AP, SAS...

**Comment by parthp08** [comment]
yes, where will you add them in this repo?

**Comment by parthp08** [comment]
and don't you think examples are needed. i had to look into files to understand how to do something.  if there are some examples (like one example in PyFme) it will be easier to start with.

**Comment by AlexS12** [comment]
> yes, where will you add them in this repo?

As a first step I would create a new `src/math` folder

**Comment by AlexS12** [comment]
> and don't you think examples are needed. i had to look into files to understand how to do something. if there are some examples (like one example in PyFme) it will be easier to start with.

Right now, the most similar thing to that are test files: https://github.com/AlexS12/FlightMechanics.jl/tree/master/test

you can run them like this:
```
Pkg> test FlightMechanics
```

But if you find it useful, we could create a separate repo with some example notebooks / scripts

**Comment by parthp08** [comment]
i will create example scripts(based on examples and tables given in stevens) in jupyter notebooks in separate repo. by doing so, i can also look into all codes so that i better understand all the files before making any future commits.

**Comment by AlexS12** [comment]
I think that after merging #35 we can close this issue.

We can continue opening issues with the new features we wan to implement: such as integration, linearization...  :smile: 

Feel free to open new issues with the new features when you are ready

**Comment by parthp08** [comment]
next I'm thinking of linearization as once we have A and B matrix and transfer function we can do control stuffs.
