### ISSUE TITLE
[Question] Capabilities 

### ISSUE THREAD

**Issue by galleon** [AlexS12/FlightMechanics.jl#47]
Hi Alex

Thanks for your work. I am currently using JSBSim and its python interface to simulate the taxing of an aircraft. Would I be able to do the same with current master of FlightMechanics.jl

Thanks

**Comment by AlexS12** [comment]
Hi @galleon, thanks for your interest. Unfortunately, FlightMechanics.jl is still lacking a lot of capabilities. It doesn't even integrate the a/c equations of motion yet. At the moment it's just a collection of useful (and tested) functions for flight mechanics as well as the famous F16 a/c model. I do not think it will be able to simulate the taxi soon. Probably, flying aircraft is simpler and will come first.

**Comment by galleon** [comment]
Hi @AlexS12, thanks for your quick answer.
I am not familiar yet with julia ... but isn't it possible using the F16 model to play with the ```set_thtl``` and ```pedals``` to do what I want to achieve.

**Comment by AlexS12** [comment]
Yes, I guess it would be necessary to improve the model with landing gear geometric and dynamic data and well that’s too much for me right now. Maybe in the future! Thanks for your interest!
